name: weather_app
description:  To Get the Weather

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "2.13.3"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: 3.2.4096
